### ISSUE TITLE
Can we have the Dockerfile please?

### ISSUE THREAD

**Issue by kapunakap** [mysteriumnetwork/workshop#2]

**Comment by mdomasevicius** [comment]
Not sure what you desire per this request?

The `myst` image itself can be found here https://hub.docker.com/r/mysteriumnetwork/myst/tags

The actual Dockerfile used to assemble alpine image at least (I belive) can be found https://github.com/mysteriumnetwork/node/blob/master/bin/docker/alpine/Dockerfile

**Comment by kapunakap** [comment]
The latter is what I was looking for. Thank you.
